-- 03_data.sql — content export from the current database
-- Run AFTER 01_schema.sql. Safe to edit/trim before running.

INSERT INTO public.profile SELECT * FROM json_populate_recordset(null::public.profile, '[{"id":"44274837-b61d-420d-bbe2-c44204475e37","full_name":"Priyam Singh","title":"Java Full-Stack Developer","tagline":"Reliable backends. Thoughtful frontends. Systems that hold up in production.","bio":"I''m a full-stack developer with five years of experience building production systems in Java and Spring Boot, paired with modern React frontends. I''ve shipped everything from internal tooling to customer-facing platforms handling thousands of daily users, and I''m most at home working across the whole stack — designing schemas, writing APIs, and polishing the interfaces on top of them. I care about boring reliability: clear error handling, tested code paths, and deployments that don''t surprise anyone. Currently exploring distributed systems patterns and deepening my cloud architecture practice on AWS.","avatar_url":null,"email":"priyam.singh@example.com","location":"Bengaluru, IN","created_at":"2026-08-29T12:28:13.415741+00:00","updated_at":"2026-08-29T12:28:13.415741+00:00","seo_title":null,"seo_description":null,"seo_og_image_url":null}]');

INSERT INTO public.projects SELECT * FROM json_populate_recordset(null::public.projects, '[{"id":"edc9c512-f085-403b-a61a-96d7174c58b7","slug":"orderflow","title":"OrderFlow","summary":"Order management platform processing 40k orders/day for a retail chain.","narrative":{"outcome": "Order loss dropped to zero in the first month. End-of-day reconciliation went from 90 minutes of manual work to an automated report. The system absorbed a 6x traffic spike during a holiday sale without intervention, and the event log later let the analytics team answer questions nobody had thought to ask at design time.", "problem": "The client''s order pipeline ran on spreadsheets and a legacy desktop app. Orders were lost between departments, inventory drifted from reality daily, and staff reconciled records by hand every evening. They needed a single system that could intake orders from three sales channels and keep inventory consistent in real time.", "approach": "I started with a two-week discovery phase, shadowing the warehouse and sales teams to map the actual order lifecycle before writing any code. We agreed on an event-sourced core: every state change (order placed, stock reserved, shipment dispatched) became an immutable event, which gave us an audit trail for free and made the reconciliation problem disappear by construction.", "architecture": "The backend is a modular Spring Boot service split along domain boundaries — orders, inventory, fulfillment — communicating through a transactional outbox into RabbitMQ. PostgreSQL holds the event store with optimistic locking on aggregate roots. The React frontend consumes a read-optimized projection API, so UI queries never touch the write model. Deployed on ECS behind an ALB, with blue-green deployments via CodeDeploy."},"cover_image_url":null,"gallery_urls":[],"stack_tags":["Java","Spring Boot","React","PostgreSQL"],"live_url":"https://example.com","repo_url":"https://github.com","case_study_url":null,"category":"Full-Stack App","timeframe":"2024 — 2025","role":"Lead Full-Stack Developer","is_featured":true,"is_published":true,"display_order":1,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"2066e44d-177c-4586-a991-2bcfa95734e7","slug":"authkit","title":"AuthKit","summary":"Drop-in authentication service handling 2M tokens/month across 12 internal apps.","narrative":{"outcome": "All twelve apps migrated in one quarter. New-app onboarding dropped from weeks to under a day. Refresh-token reuse detection caught two leaked tokens in the wild, both revoked before misuse. The security team now ships policy changes in one place.", "problem": "Twelve internal applications each implemented login differently — three session models, two token formats, and password policies that disagreed with each other. Rolling out a security requirement meant touching twelve codebases, and onboarding a new app took weeks.", "approach": "I designed AuthKit as a standalone identity service implementing OAuth2/OIDC with refresh-token rotation. The guiding constraint was adoption cost: each app integrated by adding a single Spring Security starter dependency and three config values. I wrote the migration guide alongside the code and onboarded the first two apps myself to prove the path.", "architecture": "Stateless JWT access tokens signed with rotating RSA keys (JWKS endpoint), refresh tokens stored in Redis with per-device family tracking for reuse detection. Spring Boot service, Postgres for identities, Redis for token state, horizontal scaling behind an internal load balancer. Rate limiting and anomaly flags live in a filter chain ahead of the token endpoint."},"cover_image_url":null,"gallery_urls":[],"stack_tags":["Java","Spring Security","Redis","Docker"],"live_url":"https://example.com","repo_url":"https://github.com","case_study_url":null,"category":"Backend API","timeframe":"2024","role":"Backend Developer","is_featured":true,"is_published":true,"display_order":2,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"b24e0471-1577-4e8d-a00b-53c7eb759e6f","slug":"schemadiff","title":"SchemaDiff","summary":"CLI tool that catches breaking database migrations before they reach CI.","narrative":{"outcome": "Breaking migrations reaching CI dropped to zero within a month of adoption. Three other teams adopted it, and the risk-tier classification became part of the team''s migration review checklist.", "problem": "Our team kept shipping migrations that broke staging — a dropped column here, a tightened constraint there — each discovered only after a failed deploy. Reviews caught some, but humans are bad at simulating DDL in their heads.", "approach": "I built SchemaDiff as a Gradle plugin plus CLI that spins up an ephemeral Postgres in Docker, applies the migration chain from main and from the PR branch, and diffs the resulting catalogs. Anything destructive or type-changing gets flagged with the exact statement that caused it.", "architecture": "The tool parses migration files in order, executes them against Testcontainers-managed Postgres instances, then queries information_schema and pg_catalog to build a normalized model of tables, columns, constraints, and indexes. The differ compares models and classifies changes by risk tier. A GitHub Action posts the report as a PR comment."},"cover_image_url":null,"gallery_urls":[],"stack_tags":["Java","PostgreSQL","Gradle","GitHub Actions"],"live_url":null,"repo_url":"https://github.com","case_study_url":null,"category":"Tool","timeframe":"2023","role":"Solo Developer","is_featured":true,"is_published":true,"display_order":3,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"53c78606-f3b7-4c2e-a24e-80a2ecdf2ab6","slug":"fleetpulse","title":"FleetPulse","summary":"Real-time telemetry dashboard for a 300-vehicle logistics fleet.","narrative":{"outcome": "Average incident response time fell from 12 minutes to under 3. Dispatchers stopped making status calls entirely within two weeks.", "problem": "Dispatchers tracked vehicles through phone calls and a map that refreshed every five minutes. During incidents, they were always working from stale data.", "approach": "Built a streaming pipeline: GPS pings ingest over MQTT, get enriched and fanned out through Redis Streams, and push to the dashboard over WebSocket. The UI renders 300 live positions with sub-second latency.", "architecture": "Spring WebFlux for the reactive ingest path, Redis Streams as the buffer, Postgres for historical trips. React frontend with a canvas-based map layer, virtualized lists, and server-driven alert rules."},"cover_image_url":null,"gallery_urls":[],"stack_tags":["Java","Spring WebFlux","React","Redis"],"live_url":"https://example.com","repo_url":"https://github.com","case_study_url":null,"category":"Full-Stack App","timeframe":"2023","role":"Full-Stack Developer","is_featured":false,"is_published":true,"display_order":4,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"92fd3605-ea8e-4a3c-ae33-21cb391ae511","slug":"reportforge","title":"ReportForge","summary":"Scheduled reporting API generating 5k PDF reports weekly for finance teams.","narrative":{"outcome": "Around 36 team-hours of manual work eliminated weekly. Report errors from manual formatting disappeared, and audit got a complete run history.", "problem": "Finance teams assembled weekly reports by exporting CSVs and formatting them manually — roughly four hours of work per report, every week, across nine teams.", "approach": "I built a report-definition API where teams declare queries, layout templates, and schedules. A batch cluster renders PDFs overnight and delivers them to S3 with signed links.", "architecture": "Spring Batch jobs partitioned by report definition, PostgreSQL for definitions and run history, S3 for artifacts. Idempotent job design with checkpointing so a failed render resumes rather than restarts."},"cover_image_url":null,"gallery_urls":[],"stack_tags":["Java","Spring Batch","PostgreSQL","AWS S3"],"live_url":null,"repo_url":"https://github.com","case_study_url":null,"category":"Backend API","timeframe":"2022 — 2023","role":"Backend Developer","is_featured":false,"is_published":true,"display_order":5,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"f80caa64-75a1-4694-9ea5-868c89bf7263","slug":"loglens","title":"LogLens","summary":"Lightweight log search CLI used daily by a 15-person engineering team.","narrative":{"outcome": "Median time-to-answer during incidents dropped visibly; the shared query file became living documentation of how the team debugs.", "problem": "Grepping gigabytes of structured JSON logs was slow and the queries were unrepeatable — everyone had their own incantation, and nobody remembered anyone else''s.", "approach": "LogLens indexes JSON logs into a local SQLite FTS index and exposes a small query language for common filters (service, level, trace ID, time range). Compiled to a native binary with GraalVM so it starts instantly.", "architecture": "Streaming parser with backpressure, incremental indexing so repeat queries over the same files are instant, and shareable named queries stored in a team config file."},"cover_image_url":null,"gallery_urls":[],"stack_tags":["Java","GraalVM","SQLite"],"live_url":null,"repo_url":"https://github.com","case_study_url":null,"category":"Tool","timeframe":"2022","role":"Solo Developer","is_featured":false,"is_published":true,"display_order":6,"created_at":"2026-08-29T12:28:13.415741+00:00"}]');

INSERT INTO public.experience SELECT * FROM json_populate_recordset(null::public.experience, '[{"id":"82b24d93-672d-45bd-a3b5-44d175136509","company":"NovaTech Solutions","role":"Senior Software Engineer","location":"Bengaluru, IN","start_date":"2024-03-01","end_date":null,"description":["Own the order-processing platform (Spring Boot, Kafka) handling ~2M events/day; cut p95 latency 38% via batching and cache rework.","Led migration of a legacy monolith module into 4 Spring services behind an API gateway with zero-downtime cutover.","Mentor two junior engineers; introduced contract testing with Pact across service boundaries."],"stack_tags":["Java 21","Spring Boot","Kafka","PostgreSQL","AWS","Docker"],"display_order":1,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"91f71b46-946f-4938-9611-38f3f728da10","company":"Vertex Systems","role":"Software Development Engineer II","location":"Hyderabad, IN","start_date":"2022-06-01","end_date":"2024-02-29","description":["Built a multi-tenant billing API (Spring Boot, Hibernate) adopted by 40+ enterprise customers.","Shipped a React/TypeScript admin console that replaced a legacy JSP UI, halving support tickets.","Set up CI/CD pipelines (GitHub Actions, Docker) reducing release time from hours to ~15 minutes."],"stack_tags":["Java","Spring Boot","Hibernate","React","TypeScript","GitHub Actions"],"display_order":2,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"004fdc19-4dc7-43e7-b80a-f410639588f6","company":"CodeLab Technologies","role":"Software Development Engineer","location":"Pune, IN","start_date":"2021-07-01","end_date":"2022-05-31","description":["Developed REST APIs for an inventory management product serving 200+ retail clients.","Optimized slow PostgreSQL queries (indexing, query rewrites), improving report generation 5x.","Wrote integration tests with Testcontainers, raising coverage from 30% to 75%."],"stack_tags":["Java","Spring MVC","PostgreSQL","Redis","JUnit","Testcontainers"],"display_order":3,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"cffe26ea-544c-4969-816f-09cf309f461d","company":"ByteBase Software","role":"Software Engineering Intern","location":"Remote","start_date":"2021-01-01","end_date":"2021-06-30","description":["Built internal tooling in Java and React to automate QA data seeding, saving the team ~6 hrs/week.","Contributed bug fixes to a Spring Boot microservices codebase under code review."],"stack_tags":["Java","Spring Boot","React","MySQL","Git"],"display_order":4,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}]');

INSERT INTO public.skills SELECT * FROM json_populate_recordset(null::public.skills, '[{"id":"58bfbdc2-f419-4a54-af83-5d37e7ae629d","name":"Java","category":"Backend","proficiency":5,"icon_key":"coffee","display_order":1,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"3c60453e-b36c-4d42-ae9e-120bba6743e5","name":"Spring Boot","category":"Backend","proficiency":5,"icon_key":"leaf","display_order":2,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"3781d609-d276-46b8-a933-776a904910d4","name":"Hibernate / JPA","category":"Backend","proficiency":4,"icon_key":"layers","display_order":3,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"891f2e9a-c433-49e9-af3e-ae659ad8c321","name":"REST APIs","category":"Backend","proficiency":5,"icon_key":"workflow","display_order":4,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"7b5ce11e-9dad-4165-985b-af0e699f54f6","name":"Microservices","category":"Backend","proficiency":4,"icon_key":"server","display_order":5,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"6704696e-3f2a-4d43-b5b7-d0b34d93d108","name":"React","category":"Frontend","proficiency":4,"icon_key":"braces","display_order":1,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"ea77464e-f255-41a0-9816-8e289b929d97","name":"TypeScript","category":"Frontend","proficiency":4,"icon_key":"braces","display_order":2,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"78d865a0-dba1-45dd-be58-6867e38468c7","name":"Next.js","category":"Frontend","proficiency":3,"icon_key":"layers","display_order":3,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"0bd5909d-b444-4f87-bc25-8102c29b44b5","name":"Tailwind CSS","category":"Frontend","proficiency":4,"icon_key":"layers","display_order":4,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"17ffd26f-c2f6-44b6-97bc-c19ef0eb3c0d","name":"Docker","category":"DevOps","proficiency":4,"icon_key":"container","display_order":1,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"b91dbc61-bde2-4f69-ac82-6394910ec55c","name":"AWS","category":"DevOps","proficiency":3,"icon_key":"cloud","display_order":2,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"8151b360-65c1-4f38-9a72-53bf179f1eb1","name":"CI/CD","category":"DevOps","proficiency":4,"icon_key":"workflow","display_order":3,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"dedef2cc-dc99-465e-bbe0-1e49dfaf1247","name":"Linux","category":"DevOps","proficiency":4,"icon_key":"terminal","display_order":4,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"142463c8-d728-4ddc-801a-8d66f90083cf","name":"PostgreSQL","category":"Database","proficiency":4,"icon_key":"database","display_order":1,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"8dda9ecc-8e54-4beb-99e3-932dd5720e42","name":"MySQL","category":"Database","proficiency":4,"icon_key":"database","display_order":2,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"16bb1be8-4bb8-4af0-850e-83155a69d8f7","name":"Redis","category":"Database","proficiency":3,"icon_key":"database","display_order":3,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"0a90619c-7bbf-4ddb-896c-457f343ff916","name":"Git","category":"Tools","proficiency":5,"icon_key":"git","display_order":1,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"e55b8299-4d29-4087-b7e4-90e43d9eaa03","name":"Maven / Gradle","category":"Tools","proficiency":4,"icon_key":"terminal","display_order":2,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"3ecdb585-8385-4cbe-8b45-fa66a72b1344","name":"IntelliJ IDEA","category":"Tools","proficiency":5,"icon_key":"terminal","display_order":3,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"3ee9f6e9-9818-4ece-be97-607e04b4536d","name":"Postman","category":"Tools","proficiency":4,"icon_key":"workflow","display_order":4,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}]');

INSERT INTO public.social_links SELECT * FROM json_populate_recordset(null::public.social_links, '[{"id":"a47227c4-fa72-4ece-9a05-48a3dd397c2e","platform":"Email","url":"mailto:priyam.singh@example.com","display_order":1,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"3d9fe881-160e-431d-a6c6-6d5d3180f02f","platform":"LinkedIn","url":"https://linkedin.com/in/priyamsingh","display_order":2,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}, 
 {"id":"660ff86b-97c2-46f1-b950-6e58090bb82e","platform":"GitHub","url":"https://github.com/priyamsingh","display_order":3,"is_published":true,"created_at":"2026-08-29T12:28:13.415741+00:00"}]');

INSERT INTO public.resume_versions SELECT * FROM json_populate_recordset(null::public.resume_versions, '[{"id":"6c268593-28f2-4c92-baa3-54c16c99e8f1","file_url":"/resume.pdf","version_label":"Updated Aug 2026","file_size_label":"PDF · 184 KB","is_active":true,"created_at":"2026-08-29T12:28:13.415741+00:00","updated_at":"2026-08-29T12:28:13.415741+00:00"}]');

INSERT INTO public.coding_stats SELECT * FROM json_populate_recordset(null::public.coding_stats, '[]');

